# Generated by Django 4.1.7 on 2023-03-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_planet', '0002_alter_category_options_alter_planet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Фото'),
        ),
    ]
