# Generated by Django 4.1.7 on 2023-03-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_planet', '0004_alter_planet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='bought',
            field=models.TextField(null=True, verbose_name='Покупка'),
        ),
    ]
